---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: local-path-provisioner
  namespace: local-path-provisioner
spec:
  # gitImplementation: go-git
  interval: 1d
  timeout: 5m
  ref:
    tag: v0.0.24
  url: https://github.com/rancher/local-path-provisioner.git
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/deploy/chart/local-path-provisioner
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: local-path-provisioner
spec:
  interval: 10m
  chart:
    spec:
      interval: 5m
      chart: deploy/chart/local-path-provisioner
      version: 0.0.24
      sourceRef:
        kind: GitRepository
        name: local-path-provisioner
