apiVersion: v1
kind: Namespace
metadata:
  name: postgres-cluster
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-postgres-cluster
  namespace: postgres-cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-cluster-reconciler
  namespace: postgres-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: sa-postgres-cluster
  namespace: postgres-cluster
